### PR TITLE
Ensure that backtick removal only affects example usage

### LINKED ISSUE #3: Double space with backticks in descriptions
Double space when cyan coloured with `<fg=cyan>  $1</>` also affects when there are backticks in the description. This isn't really an issue, but looks slightly odd.

https://github.com/BrainMaestro/tldr-php/blob/f7783297c56e74828e880b9d85819f3d64accb35/src/Page.php#L90

I guess something like this resolves it, but doesn't seem like a good workaround.

```php
// color all text in example command usage
'/^`(.+)`/m' => '<fg=cyan>  $1</>',
'/`(.+)`/' => '<fg=cyan>$1</>',
```

Example screenshot

### PR DESCRIPTION
**Pull request by BrainMaestro**
Fixes #3

### CODE REVIEW

**Comment by owenvoke** [comment]
This seems fine. I agree that maybe RegEx isn't the best, but it's ok for this I guess.

As an alternative to the last one, you could include another like so:
```php
            // color all text in example command usage
            '/^`(.+)`$/m' => '<fg=cyan>  $1</>',
            // color all other backticked text
            '/`(.+)`/m' => '<fg=yellow>$1</>',
```

This makes a distinction between backticks in non-example content. What do you think?

Example

**Comment by BrainMaestro** [comment]
I think it's fine. I also made a change to stop coloring the whole example usage like the node client does. Let me know what you think
image

**Comment by owenvoke** [comment]
I think that looks great. 👍

**Comment by BrainMaestro** [comment]
Cool. I was thinking of implementing some of the functionality in https://github.com/tldr-pages/tldr/wiki/Minimum-specifications-for-TLDR-command-line-clients. Let me know if you're interested

**Comment by owenvoke** [comment]
I'd be interested in helping. Looks like that should be fine.

**Comment by BrainMaestro** [comment]
Okay great, I'll open some issues in the next few days, and you can pick some to work on

**Pull request merged**
